name: Test

on:
  pull_request:

jobs:
  test:
    name: go test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Test
        run: go test ./...


# vim: set ts=2 sts=2 sw=2 et:
